PiOS switch

diff --git a/apps/aarch64-linux/pios-switch b/apps/aarch64-linux/pios-switch
--- a/apps/aarch64-linux/pios-switch
+++ b/apps/aarch64-linux/pios-switch
@@ -1,12 +1,4 @@
 #!/bin/sh -e
 
-GREEN='\033[1;32m'
-YELLOW='\033[1;33m'
-NC='\033[0m'
-
-FLAKE="pios"
-SYSTEM="homeConfigurations.$FLAKE.system"
-
-echo "${YELLOW}Starting build...${NC}"
-nix --experimental-features 'nix-command flakes' build .#$SYSTEM
+home-manager switch --flake . || { echo "Failed to switch to initial generation"; exit 1; }
 
